import { fetchPlayers, fetchPlayerCount } from "../services/ipl-api";

export type IplPlayerRow = {
  name: string;
  meta: { shortened: boolean; fullName: string };
};

const LS_PLAYER_COUNT_KEY = "stumpd-ipl-puzzle-count";

/**
 * Fetches the player count from the API, compares with the locally stored
 * count, and only fetches the full player list when the count has changed.
 * Returns `null` when the hardcoded data is still up-to-date.
 */
export async function fetchIplPlayersFromAPI(): Promise<IplPlayerRow[] | null> {
  const apiCount = await fetchPlayerCount();

  let storedCount: number | null = null;
  try {
    const raw = localStorage.getItem(LS_PLAYER_COUNT_KEY);
    if (raw != null) storedCount = parseInt(raw, 10);
  } catch { /* SSR / private mode */ }

  if (storedCount === apiCount) return null;

  const res = await fetchPlayers();
  if (!res.ok) throw new Error(`Failed to fetch IPL players: ${res.status}`);
  const json = await res.json();
  const rows: unknown[] = json.data ?? [];

  try {
    localStorage.setItem(LS_PLAYER_COUNT_KEY, String(apiCount));
  } catch { /* quota / private mode */ }

  return rows.map((r: any) => ({
    name: r.name,
    meta: {
      shortened: Boolean(r.is_shortened),
      fullName: r.full_name,
    },
  }));
}

export const iplPlayers: IplPlayerRow[] = [
  { "name": "MS", "meta": {"shortened":false,"fullName":"MS Dhoni"} },
  { "name": "DHONI", "meta": {"shortened":false,"fullName":"MS Dhoni"} },
  { "name": "SACHI", "meta": {"shortened":true,"fullName":"Sachin Tendulkar"} },
  { "name": "TENDU", "meta": {"shortened":true,"fullName":"Sachin Tendulkar"} },
  { "name": "SOURA", "meta": {"shortened":true,"fullName":"Sourav Ganguly"} },
  { "name": "GANGU", "meta": {"shortened":true,"fullName":"Sourav Ganguly"} },
  { "name": "RAHUL", "meta": {"shortened":false,"fullName":"Rahul Dravid"} },
  { "name": "DRAVI", "meta": {"shortened":true,"fullName":"Rahul Dravid"} },
  { "name": "JASPR", "meta": {"shortened":true,"fullName":"Jasprit Bumrah"} },
  { "name": "BUMRA", "meta": {"shortened":true,"fullName":"Jasprit Bumrah"} },
  { "name": "RAVIN", "meta": {"shortened":true,"fullName":"Ravindra Jadeja"} },
  { "name": "JADEJ", "meta": {"shortened":true,"fullName":"Ravindra Jadeja"} },
  { "name": "YUZVE", "meta": {"shortened":true,"fullName":"Yuzvendra Chahal"} },
  { "name": "CHAHA", "meta": {"shortened":true,"fullName":"Yuzvendra Chahal"} },
  { "name": "RISHA", "meta": {"shortened":true,"fullName":"Rishabh Pant"} },
  { "name": "PANT", "meta": {"shortened":false,"fullName":"Rishabh Pant"} },
  { "name": "ROHIT", "meta": {"shortened":false,"fullName":"Rohit Sharma"} },
  { "name": "SHARM", "meta": {"shortened":true,"fullName":"Rohit Sharma"} },
  { "name": "VIREN", "meta": {"shortened":true,"fullName":"Virender Sehwag"} },
  { "name": "SEHWA", "meta": {"shortened":true,"fullName":"Virender Sehwag"} },
  { "name": "YUVRA", "meta": {"shortened":true,"fullName":"Yuvraj Singh"} },
  { "name": "SINGH", "meta": {"shortened":false,"fullName":"Yuvraj Singh"} },
  { "name": "SURES", "meta": {"shortened":true,"fullName":"Suresh Raina"} },
  { "name": "RAINA", "meta": {"shortened":false,"fullName":"Suresh Raina"} },
  { "name": "GAUTA", "meta": {"shortened":true,"fullName":"Gautam Gambhir"} },
  { "name": "GAMBH", "meta": {"shortened":true,"fullName":"Gautam Gambhir"} },
  { "name": "SHIKH", "meta": {"shortened":true,"fullName":"Shikhar Dhawan"} },
  { "name": "DHAWA", "meta": {"shortened":true,"fullName":"Shikhar Dhawan"} },
  { "name": "KL", "meta": {"shortened":false,"fullName":"KL Rahul"} },
  { "name": "RAHUL", "meta": {"shortened":false,"fullName":"KL Rahul"} },
  { "name": "AJINK", "meta": {"shortened":true,"fullName":"Ajinkya Rahane"} },
  { "name": "RAHAN", "meta": {"shortened":true,"fullName":"Ajinkya Rahane"} },
  { "name": "CHETE", "meta": {"shortened":true,"fullName":"Cheteshwar Pujara"} },
  { "name": "PUJAR", "meta": {"shortened":true,"fullName":"Cheteshwar Pujara"} },
  { "name": "HARDI", "meta": {"shortened":true,"fullName":"Hardik Pandya"} },
  { "name": "PANDY", "meta": {"shortened":true,"fullName":"Hardik Pandya"} },
  { "name": "SURYA", "meta": {"shortened":true,"fullName":"Suryakumar Yadav"} },
  { "name": "YADAV", "meta": {"shortened":false,"fullName":"Suryakumar Yadav"} },
  { "name": "MOHAM", "meta": {"shortened":true,"fullName":"Mohammed Shami"} },
  { "name": "SHAMI", "meta": {"shortened":false,"fullName":"Mohammed Shami"} },
  { "name": "RAVIC", "meta": {"shortened":true,"fullName":"Ravichandran Ashwin"} },
  { "name": "ASHWI", "meta": {"shortened":true,"fullName":"Ravichandran Ashwin"} },
  { "name": "ISHAN", "meta": {"shortened":false,"fullName":"Ishan Kishan"} },
  { "name": "KISHA", "meta": {"shortened":true,"fullName":"Ishan Kishan"} },
  { "name": "SANJU", "meta": {"shortened":false,"fullName":"Sanju Samson"} },
  { "name": "SAMSO", "meta": {"shortened":true,"fullName":"Sanju Samson"} },
  { "name": "RINKU", "meta": {"shortened":false,"fullName":"Rinku Singh"} },
  { "name": "SINGH", "meta": {"shortened":false,"fullName":"Rinku Singh"} },
  { "name": "TILAK", "meta": {"shortened":false,"fullName":"Tilak Varma"} },
  { "name": "VARMA", "meta": {"shortened":false,"fullName":"Tilak Varma"} },
  { "name": "YASHA", "meta": {"shortened":true,"fullName":"Yashasvi Jaiswal"} },
  { "name": "JAISW", "meta": {"shortened":true,"fullName":"Yashasvi Jaiswal"} },
  { "name": "SHUBM", "meta": {"shortened":true,"fullName":"Shubman Gill"} },
  { "name": "GILL", "meta": {"shortened":false,"fullName":"Shubman Gill"} },
  { "name": "DEEPA", "meta": {"shortened":true,"fullName":"Deepak Chahar"} },
  { "name": "CHAHA", "meta": {"shortened":true,"fullName":"Deepak Chahar"} },
  { "name": "KULDE", "meta": {"shortened":true,"fullName":"Kuldeep Yadav"} },
  { "name": "YADAV", "meta": {"shortened":false,"fullName":"Kuldeep Yadav"} },
  { "name": "ARSHD", "meta": {"shortened":true,"fullName":"Arshdeep Singh"} },
  { "name": "SINGH", "meta": {"shortened":false,"fullName":"Arshdeep Singh"} },
  { "name": "MOHAM", "meta": {"shortened":true,"fullName":"Mohammed Siraj"} },
  { "name": "SIRAJ", "meta": {"shortened":false,"fullName":"Mohammed Siraj"} },
  { "name": "AXAR", "meta": {"shortened":false,"fullName":"Axar Patel"} },
  { "name": "PATEL", "meta": {"shortened":false,"fullName":"Axar Patel"} },
  { "name": "RUTUR", "meta": {"shortened":true,"fullName":"Ruturaj Gaikwad"} },
  { "name": "GAIKW", "meta": {"shortened":true,"fullName":"Ruturaj Gaikwad"} },
  { "name": "DINES", "meta": {"shortened":true,"fullName":"Dinesh Karthik"} },
  { "name": "KARTH", "meta": {"shortened":true,"fullName":"Dinesh Karthik"} },
  { "name": "IRFAN", "meta": {"shortened":false,"fullName":"Irfan Pathan"} },
  { "name": "PATHA", "meta": {"shortened":true,"fullName":"Irfan Pathan"} },
  { "name": "VIRAT", "meta": {"shortened":false,"fullName":"Virat Kohli"} },
  { "name": "KOHLI", "meta": {"shortened":false,"fullName":"Virat Kohli"} },
  { "name": "ANIL", "meta": {"shortened":false,"fullName":"Anil Kumble"} },
  { "name": "KUMBL", "meta": {"shortened":true,"fullName":"Anil Kumble"} },
  { "name": "ZAHEE", "meta": {"shortened":true,"fullName":"Zaheer Khan"} },
  { "name": "KHAN", "meta": {"shortened":false,"fullName":"Zaheer Khan"} },
  { "name": "HARBH", "meta": {"shortened":true,"fullName":"Harbhajan Singh"} },
  { "name": "SINGH", "meta": {"shortened":false,"fullName":"Harbhajan Singh"} },
  { "name": "KAPIL", "meta": {"shortened":false,"fullName":"Kapil Dev"} },
  { "name": "DEV", "meta": {"shortened":false,"fullName":"Kapil Dev"} },
  { "name": "SUNIL", "meta": {"shortened":false,"fullName":"Sunil Gavaskar"} },
  { "name": "GAVAS", "meta": {"shortened":true,"fullName":"Sunil Gavaskar"} },
  { "name": "VVS", "meta": {"shortened":false,"fullName":"VVS Laxman"} },
  { "name": "LAXMA", "meta": {"shortened":true,"fullName":"VVS Laxman"} },
  { "name": "STEVE", "meta": {"shortened":false,"fullName":"Steve Smith"} },
  { "name": "SMITH", "meta": {"shortened":false,"fullName":"Steve Smith"} },
  { "name": "DAVID", "meta": {"shortened":false,"fullName":"David Warner"} },
  { "name": "WARNE", "meta": {"shortened":true,"fullName":"David Warner"} },
  { "name": "PAT", "meta": {"shortened":false,"fullName":"Pat Cummins"} },
  { "name": "CUMMI", "meta": {"shortened":true,"fullName":"Pat Cummins"} },
  { "name": "RICKY", "meta": {"shortened":false,"fullName":"Ricky Ponting"} },
  { "name": "PONTI", "meta": {"shortened":true,"fullName":"Ricky Ponting"} },
  { "name": "SHANE", "meta": {"shortened":false,"fullName":"Shane Warne"} },
  { "name": "WARNE", "meta": {"shortened":false,"fullName":"Shane Warne"} },
  { "name": "ADAM", "meta": {"shortened":false,"fullName":"Adam Gilchrist"} },
  { "name": "GILCH", "meta": {"shortened":true,"fullName":"Adam Gilchrist"} },
  { "name": "MITCH", "meta": {"shortened":true,"fullName":"Mitchell Starc"} },
  { "name": "STARC", "meta": {"shortened":false,"fullName":"Mitchell Starc"} },
  { "name": "TRAVI", "meta": {"shortened":true,"fullName":"Travis Head"} },
  { "name": "HEAD", "meta": {"shortened":false,"fullName":"Travis Head"} },
  { "name": "MATTH", "meta": {"shortened":true,"fullName":"Matthew Hayden"} },
  { "name": "HAYDE", "meta": {"shortened":true,"fullName":"Matthew Hayden"} },
  { "name": "MITCH", "meta": {"shortened":true,"fullName":"Mitchell Johnson"} },
  { "name": "JOHNS", "meta": {"shortened":true,"fullName":"Mitchell Johnson"} },
  { "name": "GLENN", "meta": {"shortened":false,"fullName":"Glenn McGrath"} },
  { "name": "MCGRA", "meta": {"shortened":true,"fullName":"Glenn McGrath"} },
  { "name": "JOSH", "meta": {"shortened":false,"fullName":"Josh Hazlewood"} },
  { "name": "HAZLE", "meta": {"shortened":true,"fullName":"Josh Hazlewood"} },
  { "name": "CAMER", "meta": {"shortened":true,"fullName":"Cameron Green"} },
  { "name": "GREEN", "meta": {"shortened":false,"fullName":"Cameron Green"} },
  { "name": "JOE", "meta": {"shortened":false,"fullName":"Joe Root"} },
  { "name": "ROOT", "meta": {"shortened":false,"fullName":"Joe Root"} },
  { "name": "BEN", "meta": {"shortened":false,"fullName":"Ben Stokes"} },
  { "name": "STOKE", "meta": {"shortened":true,"fullName":"Ben Stokes"} },
  { "name": "JAMES", "meta": {"shortened":false,"fullName":"James Anderson"} },
  { "name": "ANDER", "meta": {"shortened":true,"fullName":"James Anderson"} },
  { "name": "STUAR", "meta": {"shortened":true,"fullName":"Stuart Broad"} },
  { "name": "BROAD", "meta": {"shortened":false,"fullName":"Stuart Broad"} },
  { "name": "KEVIN", "meta": {"shortened":false,"fullName":"Kevin Pietersen"} },
  { "name": "PIETE", "meta": {"shortened":true,"fullName":"Kevin Pietersen"} },
  { "name": "JOFRA", "meta": {"shortened":false,"fullName":"Jofra Archer"} },
  { "name": "ARCHE", "meta": {"shortened":true,"fullName":"Jofra Archer"} },
  { "name": "ANDRE", "meta": {"shortened":true,"fullName":"Andrew Flintoff"} },
  { "name": "FLINT", "meta": {"shortened":true,"fullName":"Andrew Flintoff"} },
  { "name": "JONNY", "meta": {"shortened":false,"fullName":"Jonny Bairstow"} },
  { "name": "BAIRS", "meta": {"shortened":true,"fullName":"Jonny Bairstow"} },
  { "name": "HARRY", "meta": {"shortened":false,"fullName":"Harry Brook"} },
  { "name": "BROOK", "meta": {"shortened":false,"fullName":"Harry Brook"} },
  { "name": "CHRIS", "meta": {"shortened":false,"fullName":"Chris Gayle"} },
  { "name": "GAYLE", "meta": {"shortened":false,"fullName":"Chris Gayle"} },
  { "name": "BRIAN", "meta": {"shortened":false,"fullName":"Brian Lara"} },
  { "name": "LARA", "meta": {"shortened":false,"fullName":"Brian Lara"} },
  { "name": "KIERO", "meta": {"shortened":true,"fullName":"Kieron Pollard"} },
  { "name": "POLLA", "meta": {"shortened":true,"fullName":"Kieron Pollard"} },
  { "name": "ANDRE", "meta": {"shortened":false,"fullName":"Andre Russell"} },
  { "name": "RUSSE", "meta": {"shortened":true,"fullName":"Andre Russell"} },
  { "name": "DWAYN", "meta": {"shortened":true,"fullName":"Dwayne Bravo"} },
  { "name": "BRAVO", "meta": {"shortened":false,"fullName":"Dwayne Bravo"} },
  { "name": "SUNIL", "meta": {"shortened":false,"fullName":"Sunil Narine"} },
  { "name": "NARIN", "meta": {"shortened":true,"fullName":"Sunil Narine"} },
  { "name": "VIVIA", "meta": {"shortened":true,"fullName":"Vivian Richards"} },
  { "name": "RICHA", "meta": {"shortened":true,"fullName":"Vivian Richards"} },
  { "name": "NICHO", "meta": {"shortened":true,"fullName":"Nicholas Pooran"} },
  { "name": "POORA", "meta": {"shortened":true,"fullName":"Nicholas Pooran"} },
  { "name": "DALE", "meta": {"shortened":false,"fullName":"Dale Steyn"} },
  { "name": "STEYN", "meta": {"shortened":false,"fullName":"Dale Steyn"} },
  { "name": "JACQU", "meta": {"shortened":true,"fullName":"Jacques Kallis"} },
  { "name": "KALLI", "meta": {"shortened":true,"fullName":"Jacques Kallis"} },
  { "name": "KAGIS", "meta": {"shortened":true,"fullName":"Kagiso Rabada"} },
  { "name": "RABAD", "meta": {"shortened":true,"fullName":"Kagiso Rabada"} },
  { "name": "AB", "meta": {"shortened":false,"fullName":"AB de Villiers"} },
  { "name": "DEVIL", "meta": {"shortened":true,"fullName":"AB de Villiers"} },
  { "name": "QUINT", "meta": {"shortened":true,"fullName":"Quinton de Kock"} },
  { "name": "DE KO", "meta": {"shortened":true,"fullName":"Quinton de Kock"} },
  { "name": "DAVID", "meta": {"shortened":false,"fullName":"David Miller"} },
  { "name": "MILLE", "meta": {"shortened":true,"fullName":"David Miller"} },
  { "name": "TEMBA", "meta": {"shortened":false,"fullName":"Temba Bavuma"} },
  { "name": "BAVUM", "meta": {"shortened":true,"fullName":"Temba Bavuma"} },
  { "name": "FAF", "meta": {"shortened":false,"fullName":"Faf du Plessis"} },
  { "name": "DU PL", "meta": {"shortened":true,"fullName":"Faf du Plessis"} },
  { "name": "KANE", "meta": {"shortened":false,"fullName":"Kane Williamson"} },
  { "name": "WILLI", "meta": {"shortened":true,"fullName":"Kane Williamson"} },
  { "name": "BREND", "meta": {"shortened":true,"fullName":"Brendon McCullum"} },
  { "name": "MCCUL", "meta": {"shortened":true,"fullName":"Brendon McCullum"} },
  { "name": "TRENT", "meta": {"shortened":false,"fullName":"Trent Boult"} },
  { "name": "BOULT", "meta": {"shortened":false,"fullName":"Trent Boult"} },
  { "name": "MARTI", "meta": {"shortened":true,"fullName":"Martin Guptill"} },
  { "name": "GUPTI", "meta": {"shortened":true,"fullName":"Martin Guptill"} },
  { "name": "DEVON", "meta": {"shortened":false,"fullName":"Devon Conway"} },
  { "name": "CONWA", "meta": {"shortened":true,"fullName":"Devon Conway"} },
  { "name": "KUMAR", "meta": {"shortened":false,"fullName":"Kumar Sangakkara"} },
  { "name": "SANGA", "meta": {"shortened":true,"fullName":"Kumar Sangakkara"} },
  { "name": "MAHEL", "meta": {"shortened":true,"fullName":"Mahela Jayawardena"} },
  { "name": "JAYAW", "meta": {"shortened":true,"fullName":"Mahela Jayawardena"} },
  { "name": "MUTTI", "meta": {"shortened":true,"fullName":"Muttiah Muralitharan"} },
  { "name": "MURAL", "meta": {"shortened":true,"fullName":"Muttiah Muralitharan"} },
  { "name": "LASIT", "meta": {"shortened":true,"fullName":"Lasith Malinga"} },
  { "name": "MALIN", "meta": {"shortened":true,"fullName":"Lasith Malinga"} },
  { "name": "WANIN", "meta": {"shortened":true,"fullName":"Wanindu Hasaranga"} },
  { "name": "HASAR", "meta": {"shortened":true,"fullName":"Wanindu Hasaranga"} },
  { "name": "TILLA", "meta": {"shortened":true,"fullName":"Tillakaratne Dilshan"} },
  { "name": "DILSH", "meta": {"shortened":true,"fullName":"Tillakaratne Dilshan"} },
  { "name": "SHAKI", "meta": {"shortened":true,"fullName":"Shakib Al Hasan"} },
  { "name": "AL HA", "meta": {"shortened":true,"fullName":"Shakib Al Hasan"} },
  { "name": "TAMIM", "meta": {"shortened":false,"fullName":"Tamim Iqbal"} },
  { "name": "IQBAL", "meta": {"shortened":false,"fullName":"Tamim Iqbal"} },
  { "name": "MUSHF", "meta": {"shortened":true,"fullName":"Mushfiqur Rahim"} },
  { "name": "RAHIM", "meta": {"shortened":false,"fullName":"Mushfiqur Rahim"} },
  { "name": "MUSTA", "meta": {"shortened":true,"fullName":"Mustafizur Rahman"} },
  { "name": "RAHMA", "meta": {"shortened":true,"fullName":"Mustafizur Rahman"} },
  { "name": "BABAR", "meta": {"shortened":false,"fullName":"Babar Azam"} },
  { "name": "AZAM", "meta": {"shortened":false,"fullName":"Babar Azam"} },
  { "name": "MOHAM", "meta": {"shortened":true,"fullName":"Mohammad Rizwan"} },
  { "name": "RIZWA", "meta": {"shortened":true,"fullName":"Mohammad Rizwan"} },
  { "name": "SHAHE", "meta": {"shortened":true,"fullName":"Shaheen Afridi"} },
  { "name": "AFRID", "meta": {"shortened":true,"fullName":"Shaheen Afridi"} },
  { "name": "SHAHI", "meta": {"shortened":true,"fullName":"Shahid Afridi"} },
  { "name": "AFRID", "meta": {"shortened":true,"fullName":"Shahid Afridi"} },
  { "name": "SHOAI", "meta": {"shortened":true,"fullName":"Shoaib Akhtar"} },
  { "name": "AKHTA", "meta": {"shortened":true,"fullName":"Shoaib Akhtar"} },
  { "name": "WASIM", "meta": {"shortened":false,"fullName":"Wasim Akram"} },
  { "name": "AKRAM", "meta": {"shortened":false,"fullName":"Wasim Akram"} },
  { "name": "WAQAR", "meta": {"shortened":false,"fullName":"Waqar Younis"} },
  { "name": "YOUNI", "meta": {"shortened":true,"fullName":"Waqar Younis"} },
  { "name": "YOUNI", "meta": {"shortened":true,"fullName":"Younis Khan"} },
  { "name": "KHAN", "meta": {"shortened":false,"fullName":"Younis Khan"} },
  { "name": "FAKHA", "meta": {"shortened":true,"fullName":"Fakhar Zaman"} },
  { "name": "ZAMAN", "meta": {"shortened":false,"fullName":"Fakhar Zaman"} },
  { "name": "SARFA", "meta": {"shortened":true,"fullName":"Sarfaraz Ahmed"} },
  { "name": "AHMED", "meta": {"shortened":false,"fullName":"Sarfaraz Ahmed"} },
  { "name": "RASHI", "meta": {"shortened":true,"fullName":"Rashid Khan"} },
  { "name": "KHAN", "meta": {"shortened":false,"fullName":"Rashid Khan"} },
  { "name": "MUJEE", "meta": {"shortened":true,"fullName":"Mujeeb Ur Rahman"} },
  { "name": "UR RA", "meta": {"shortened":true,"fullName":"Mujeeb Ur Rahman"} },
  { "name": "MOHAM", "meta": {"shortened":true,"fullName":"Mohammed Nabi"} },
  { "name": "NABI", "meta": {"shortened":false,"fullName":"Mohammed Nabi"} },
  { "name": "ANDY", "meta": {"shortened":false,"fullName":"Andy Flower"} },
  { "name": "FLOWE", "meta": {"shortened":true,"fullName":"Andy Flower"} },
  { "name": "BREND", "meta": {"shortened":true,"fullName":"Brendan Taylor"} },
  { "name": "TAYLO", "meta": {"shortened":true,"fullName":"Brendan Taylor"} },
  { "name": "PAUL", "meta": {"shortened":false,"fullName":"Paul Stirling"} },
  { "name": "STIRL", "meta": {"shortened":true,"fullName":"Paul Stirling"} }
];
